spring.application.name=MPL-AUCTION
spring.datasource.url=jdbc:postgresql://13.232.247.16:5432/ca
spring.datasource.username=prashant
spring.datasource.password=Pr@sh@nt@77079413

server.port=8080

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
web-socket.config.allowed.origins=http://13.232.247.16

#spring.jpa.show-sql=true
