spring.application.name=MPL-AUCTION
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=mpl
spring.datasource.username=postgres
spring.datasource.password=postgres

server.port=8080

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.profiles.active=prod
web-socket.config.allowed.origins=http://localhost:3000

spring.jpa.show-sql=true
